"""The model registry (decision 55, 3 Oct 2026; the user: "leg de regel vast dat we toekomstig werk doen met model-versies waar we tevreden mee zijn,
waarin de ontwerpkeuzes zitten waartoe we besloten hebben").

One row per saved network in `out/` (`*.pt`): kind, reviewed status, chain, the recipe read from the checkpoint itself (head, pattern, target,
auxiliary terms, body, inputs, pool, n, seed), the hold-out numbers and the git commit from the result record beside it, and a note. Mechanical:
nothing here is typed by hand except the reviewed status file `out/MODELS_STATUS.json` — a checkpoint without an entry stops the generator (a
model that nobody has judged is not silently listed), and a status outside STATUSES is refused.

The rule the loaders enforce (`require_carried`): future work runs on a model whose status is `carried`; a read made with a `superseded`, `smoke`,
`pretrained` or `invalid` model is not evidence. `rungC_cc_transfer.py` and `probes/rungC_eval_saved.py` refuse such a model unless
`--allow-any-model` is passed, and that use is named in the record.

    python m05/model_registry.py            # writes MODELS.md
    python m05/model_registry.py --check    # exit 1 when the committed MODELS.md differs from what the checkpoints say (tests/test_model_registry.py runs it)
"""
from __future__ import annotations

import argparse
import json
import sys
import time
from pathlib import Path

import torch

M05 = Path(__file__).resolve().parents[1]
OUT = M05 / "out"
STATUS_FILE = OUT / "MODELS_STATUS.json"
REGISTRY = M05 / "MODELS.md"
STATUSES = ("carried", "superseded", "invalid", "smoke", "pretrained")
HEADER = """# Saved networks — the model registry (decision 55, 3 October 2026)

*Generated by `m05/model_registry.py` from the checkpoints in `out/` and the result records beside them; the status column is the reviewed file
`out/MODELS_STATUS.json` (a checkpoint without an entry stops the generator). **Rule (decision 55):** future work runs on a model whose status is
`carried` — a version we are satisfied with, carrying the design decisions taken (pattern, target, auxiliary terms, body, inputs). A read made with a
`superseded`, `smoke`, `pretrained` or `invalid` model is not evidence; `rungC_cc_transfer.py` and `probes/rungC_eval_saved.py` refuse such a model
unless `--allow-any-model` is given, and that use is named in the record. `python m05/model_registry.py --check` fails when this file is stale.*

| model | kind | status | chain | recipe (from the checkpoint) | hold-out (a) ratio / ω | hold-out (b) ratio / ω | commit | saved | note |
|---|---|---|---|---|---|---|---|---|---|
"""


def load_checkpoint(path: Path) -> dict:
    return torch.load(path, map_location="cpu", weights_only=False)


def kind_of(ck: dict) -> str:
    if "ctor" in ck and "args" in ck:
        return "hybrid"
    if "body_state" in ck:
        return "pretrained body"
    return "unknown"


def recipe_of(ck: dict) -> str:
    """The design choices as the checkpoint carries them (nothing inferred from the file name)."""
    if kind_of(ck) == "hybrid":
        c, a = ck["ctor"], ck["args"]
        return (f"{ck.get('head', a.get('head'))} head, pattern {ck.get('pattern')}, target {ck.get('aux_target')} (λ {ck.get('ls_lam')}), aux {ck.get('aux_mode')} "
                f"(kring {ck.get('kring_weight')}, kdiag {ck.get('kdiag_weight')} {ck.get('kdiag_mode', 'all')}), body {c.get('n_blocks')}×{c.get('n_s')} {c.get('aggregation')}"
                f"{', tensor input' if c.get('tensor_input') else ''}, sqm α {'on' if c.get('sqm_scale') else 'off'}, pair features {c.get('n_pair_features', 0)}, "
                f"hidden {c.get('hidden')}, pool {a.get('pool_layers')}, analytic {'on' if a.get('use_analytic') else 'off'}, epochs {a.get('epochs')} / patience "
                f"{a.get('patience')}, lr {a.get('lr')}, n {ck.get('n')}, seed {ck.get('seed')}")
    if kind_of(ck) == "pretrained body":
        keys = [k for k in ("aggregation", "epochs", "lr", "n_molecules", "elements", "tensor_input") if k in ck]
        return "pretrained body: " + ", ".join(f"{k} {ck[k]}" for k in keys)
    return "unknown checkpoint layout: " + ", ".join(sorted(ck)[:8])


def result_record(path: Path) -> dict | None:
    """The result json written by the run that saved the model: `<prefix>.json` for `<prefix>_model_n<n>_seed<s>.pt`, else `<stem>.json`."""
    prefix = path.name.split("_model_")[0] if "_model_" in path.name else path.stem
    p = path.parent / f"{prefix}.json"
    if not p.exists():
        return None
    with open(p, encoding="utf-8") as f:
        return json.load(f)


def commit_of(rec: dict | None, ck: dict) -> str:
    for src in (ck.get("provenance") if isinstance(ck.get("provenance"), dict) else None, (rec or {}).get("provenance")):
        if isinstance(src, dict):
            c = next((str(v) for k, v in src.items() if "commit" in k), "")
            dirty = next((v for k, v in src.items() if "dirty" in k), None)
            if c:
                return c[:9] + (" (dirty)" if dirty in (True, "True", "true", 1) else "")
    return "—"


def holdout_numbers(rec: dict | None, ck: dict, split: str) -> str:
    try:
        r = rec["curve"][str(ck["n"])]["per_seed"][int(ck["seed"])][split]
        return f"{r['coupling_ratio']:.2f} / {r['corrected_freq_rms']:.2f}"
    except (KeyError, IndexError, TypeError):
        return "—"


def read_status(status_file: Path) -> dict:
    if not status_file.exists():
        return {}
    with open(status_file, encoding="utf-8") as f:
        s = json.load(f)
    for name, e in s.items():
        if e.get("status") not in STATUSES:
            raise ValueError(f"{status_file}: {name} has status {e.get('status')!r}; allowed {STATUSES}")
    return s


def rows(out_dir: Path = OUT, status_file: Path = STATUS_FILE) -> tuple[list[dict], list[str]]:
    status = read_status(status_file)
    out, missing = [], []
    for p in sorted(out_dir.glob("*.pt")):
        if p.name not in status:
            missing.append(p.name)
            continue
        ck = load_checkpoint(p)
        rec = result_record(p)
        e = status[p.name]
        out.append(dict(model=p.name, kind=kind_of(ck), status=e["status"], chain=e.get("chain", ""), recipe=recipe_of(ck),
                        a=holdout_numbers(rec, ck, "a"), b=holdout_numbers(rec, ck, "b"), commit=commit_of(rec, ck),
                        saved=(rec or {}).get("date") or time.strftime("%Y-%m-%d %H:%M", time.localtime(p.stat().st_mtime)), note=e.get("note", "")))
    return out, missing


def render(table: list[dict]) -> str:
    body = "".join(f"| `{r['model']}` | {r['kind']} | **{r['status']}** | {r['chain']} | {r['recipe']} | {r['a']} | {r['b']} | {r['commit']} | {r['saved']} | {r['note']} |\n"
                   for r in table)
    return HEADER + body


def status_of(path: Path, status_file: Path = STATUS_FILE) -> dict | None:
    return read_status(status_file).get(Path(path).name)


def require_carried(path: Path, allow: bool = False, status_file: Path = STATUS_FILE) -> dict:
    """Decision 55: a read runs on a `carried` model. Stops with the reason otherwise; `allow` lets a named exception through (the record must say so)."""
    s = status_of(path, status_file)
    if s is None:
        raise SystemExit(f"{Path(path).name} is not in the model registry ({status_file}): give it a reviewed status first (decision 55)")
    if s["status"] != "carried" and not allow:
        raise SystemExit(f"{Path(path).name} has status {s['status']!r} in the model registry — not a base for a read (decision 55); "
                         "pass --allow-any-model to use it anyway and name that in the record")
    return s


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--out-dir", default=str(OUT))
    ap.add_argument("--status-file", default=str(STATUS_FILE))
    ap.add_argument("--registry", default=str(REGISTRY))
    ap.add_argument("--check", action="store_true", help="exit 1 if the committed registry differs from what the checkpoints say")
    a = ap.parse_args(argv)
    table, missing = rows(Path(a.out_dir), Path(a.status_file))
    if missing:
        print("model registry STOPPED: no reviewed status for " + ", ".join(missing) + f" — add them to {a.status_file}", file=sys.stderr)
        return 1
    text = render(table)
    reg = Path(a.registry)
    if a.check:
        if not reg.exists() or reg.read_text(encoding="utf-8") != text:
            print(f"model registry STALE: {reg} differs from the checkpoints — run m05/model_registry.py", file=sys.stderr)
            return 1
        print(f"model registry ok ({len(table)} models)")
        return 0
    reg.write_text(text, encoding="utf-8")
    print(f"wrote {reg} ({len(table)} models; carried: {sum(r['status'] == 'carried' for r in table)})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
