"""Regenerate data/corpus_release/RELEASES.md from every *_manifest.json (25 September 2026, weekend plan lever 3: a versioned release procedure).

    python m05/release_index.py            # writes data/corpus_release/RELEASES.md
    python m05/release_index.py --check    # exit 1 if the committed index differs from what the manifests say

One row per release: name, build time (UTC), molecules per layer, largest mode count, deck hashes, skipped folders by reason, Hessians taken from
the analytic second route, the archive's SHA-256 (first 16 hex) and whether archive and manifest are tracked by git. The archives (0.5–4 MB) stay
out of git and go to the deposit; the manifest carries every per-molecule checksum, so a reader can verify an archive against its manifest with
`build_release.py`'s `sha256`. Mechanical: nothing here is typed by hand."""
from __future__ import annotations

import argparse
import json
import subprocess
import sys
from collections import Counter
from pathlib import Path

sys.stdout.reconfigure(encoding="utf-8", errors="replace")
HERE = Path(__file__).resolve().parents[1]
REL = HERE / "data" / "corpus_release"


def tracked() -> set[str]:
    out = subprocess.run(["git", "ls-files", "data/corpus_release"], cwd=HERE, capture_output=True, text=True, check=True).stdout
    return {Path(p).name for p in out.split("\n") if p}


def build() -> str:
    trk = tracked()
    rows = []
    for mp in sorted(REL.glob("*_manifest.json")):
        m = json.loads(mp.read_text(encoding="utf-8"))
        name = mp.name[: -len("_manifest.json")]
        layers = Counter(x["layer"] for x in m["molecules"])
        # a --layer build lists the other layers' molecules as skipped with their status ("done")
        skipped = Counter("other layer" if x[1] == "done" else x[1] for x in m.get("skipped", []) if len(x) > 1)
        npz = REL / f"{name}.npz"
        per_layer = " ".join(f"{k} {v}" for k, v in sorted(layers.items()))
        skipped_s = " ".join(f"{k} {v}" for k, v in sorted(skipped.items())) or "—"
        archive = ("yes" if npz.name in trk else "local") if npz.exists() else "absent"
        rows.append((name, m["built_utc"], m["n_molecules"], per_layer, m["max_modes"], " ".join(m["decks"]), skipped_s,
                     len(m.get("analytic_second_route", [])), m["npz_sha256"][:16], archive, "yes" if mp.name in trk else "no"))
    cols = ["release", "built (UTC)", "molecules", "per layer", "max modes", "deck hashes", "skipped (reason n)", "second-route Hessians",
            "archive sha256[:16]", "archive in git", "manifest in git"]
    head = ("# Corpus releases (module 05)\n\n*Generated by `m05/release_index.py` from the manifests in this folder; do not edit by hand. "
            "Archives stay out of git (size); each manifest lists the SHA-256 of every Hessian file and of the archive.*\n\n"
            "| " + " | ".join(cols) + " |\n" + "|" + "---|" * len(cols) + "\n")
    return head + "".join("| " + " | ".join(str(c) for c in r) + " |\n" for r in rows)


if __name__ == "__main__":
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    text = build()
    out = REL / "RELEASES.md"
    if a.check:
        same = out.exists() and out.read_text(encoding="utf-8").replace("\r\n", "\n") == text
        print("RELEASES.md is current" if same else "RELEASES.md is STALE — run m05/release_index.py")
        sys.exit(0 if same else 1)
    out.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {out.relative_to(HERE)} ({text.count(chr(10)) - 6} releases)")
