#!/usr/bin/env python
"""Writes and executes the Module 05 notebook `deep_learning.ipynb` from source cells kept here (22 September 2026 rebuild in the
rubric's structure around the ΔH model; replaces the 12 September skeleton whose stub cells raised by design).

Rubric (Rubrics/05, Tasks 1–6): task type declared · dataset loaded and inspected with representative samples · baseline Transformer
in PyTorch with the architecture shown and the design choices explained · training with loss curves · exactly one controlled change ·
evaluation of both with metrics fit for the task and a direct comparison · a 4–6 sentence summary.

Data: `data/corpus_release/<release>.npz` written by `m05/build_release.py` (default: the layer-A file of 22 September; the E6 layer-A2
release replaces it when the corpus factory finishes). Model: `m05/deltah_model.py` (copy of the architecture sheet). Results go to
`notebook/results.json` for `make_summary.py`. Environment knobs for a quick pipeline check (not a result): M05_QUICK=1 → 3 epochs,
one seed. Run:  python notebook/make_notebook.py
"""
import json
import os
import sys
from pathlib import Path

import nbformat
import numpy as np
from nbclient import NotebookClient
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook

HERE = Path(__file__).resolve().parent
RELEASE = os.environ.get("M05_RELEASE", "layerA_2026-09-22")
cells = []


def md(s):
    cells.append(new_markdown_cell(s))


def code(s):
    cells.append(new_code_cell(s))


md(f"""# Module 05 — the ΔH model: a Transformer that predicts, per family of vibrations, how a cheap Hessian must be corrected

**Task type (declared for the rubric): sequence modelling with a Transformer.** A molecule enters as a *sequence of normal-mode tokens* —
one token per vibration of a cheap density-functional Hessian (B3LYP/6-31G*) — and the network predicts the *family block* of the
correction matrix towards a better level of theory (ωB97X/6-31G* here as the stand-in for coupled cluster): the block's diagonal is the
per-mode band shift, its off-diagonal elements are the couplings between modes of one family. A second head predicts which
mode pairs carry a large correction at all (the *support*). This is the learned prior of the Δ-probed IR pipeline (plan 05): it tells the
expensive measurement where to look.

**Dataset.** The project's own corpus of molecule Hessians, computed by its corpus factory at two levels of theory on the same
geometries (`data/corpus_release/{RELEASE}.npz` with its manifest of checksums; released on Zenodo with a DOI before submission).
Computed ab initio data — public, not synthetic in the sense of generated by a model, not AI-generated, not used in Modules 02–04
(those used the NASA PAHdb and NIST laboratory libraries). Recipe, splits, seeds and the one controlled change were fixed in
`RECIPE.md` before this notebook existed (dated amendments of 13 and 19 September 2026 restate the target as the family block).

Sections: **Setup · 1 Load and inspect · 2 Baseline model · 3 Training · 4 Controlled comparison · 5 Evaluation · 6 Summary**.""")

md("## Setup")
code(f"""import json, hashlib, math, os, sys, time
from pathlib import Path
import numpy as np, pandas as pd, torch, torch.nn as nn
%matplotlib inline
import matplotlib.pyplot as plt
sys.path.insert(0, str(Path("..") / "m05"))
from deltah_model import DeltaHModel, DeltaHConfig, block_loss
torch.set_num_threads(int(os.environ.get("M05_THREADS", "2")))
QUICK = os.environ.get("M05_QUICK") == "1"          # pipeline check only: fewer epochs, one seed — never a result
RELEASE = Path("..") / "data" / "corpus_release" / "{RELEASE}.npz"
FIG = Path("figures"); FIG.mkdir(exist_ok=True)
FAMILIES = ["CH-stretch", "CH-oop", "ring-ip", "other"]
THETA = 0.1                                          # pair label: |K_ij| >= THETA * max_k |K_kk| (RECIPE)
EPOCHS, SEEDS = (3, [0]) if QUICK else (30, [0, 1, 2])
print("torch", torch.__version__, "| release:", RELEASE.name, RELEASE.exists(), "| quick mode:", QUICK)""")

md("""## 1. Load and inspect the dataset

Each molecule is one sequence. A token holds only cheap-level information: ω/1000, the family one-hot, the mass-weighted shares of C, H,
N and O in the motion, a localisation number, the out-of-plane share and twelve atom-environment classes (which kinds of hydrogens and
carbons move). The target `K` is the correction matrix in the cheap-level mode basis, in cm⁻¹; the model never sees it as input.""")
code("""z = np.load(RELEASE); man = json.load(open(str(RELEASE).replace(".npz", "_manifest.json")))
ids, mask, tokens, family, omega, K = z["ids"], z["mask"], z["tokens"], z["family"], z["omega_cm"], z["K"]
N, M, D = tokens.shape
print(f"{N} molecules, up to {M} modes each, {D} token features; total modes {int(mask.sum()):,}; built {man['built_utc']} UTC from {man['n_molecules']} folders")
print("token layout:", man["token_layout"]); print("target:", man["target"])
print("dtypes:", tokens.dtype, family.dtype, K.dtype, "| shapes:", tokens.shape, family.shape, K.shape)
print("modes per family:", man["mode_counts_per_family"])""")
code("""# representative samples: three molecules, first six modes each
rows = []
for i in [0, N // 2, N - 1]:
    for j in range(min(6, int(mask[i].sum()))):
        rows.append(dict(molecule=ids[i], mode=j, omega_cm=round(float(omega[i, j]), 1), family=FAMILIES[family[i, j]],
                         share_C=round(float(tokens[i, j, 5]), 2), share_H=round(float(tokens[i, j, 6]), 2), K_ii_cm=round(float(K[i, j, j]), 1)))
pd.DataFrame(rows)""")
code("""# data quality: padding, symmetry of K, magnitude of the diagonal and couplings, family balance
diag = np.concatenate([np.diag(K[i])[mask[i]] for i in range(N)])
off = np.concatenate([K[i][np.ix_(mask[i], mask[i])][~np.eye(int(mask[i].sum()), dtype=bool)] for i in range(N)])
asym = max(float(np.abs(K[i][np.ix_(mask[i], mask[i])] - K[i][np.ix_(mask[i], mask[i])].T).max()) for i in range(N))
print(f"padded positions: {int((~mask).sum()):,} of {mask.size:,}; K symmetric to {asym:.1e} cm⁻¹")
print(f"diagonal (first-order shifts): median {np.median(diag):+.1f}, 5–95 % {np.percentile(diag, 5):+.1f} … {np.percentile(diag, 95):+.1f} cm⁻¹")
print(f"couplings |K_ij|: median {np.median(np.abs(off)):.2f}, 95 % {np.percentile(np.abs(off), 95):.2f}, max {np.abs(off).max():.1f} cm⁻¹")
fig, axes = plt.subplots(1, 2, figsize=(10, 3.4))
axes[0].hist(diag, bins=60, color="steelblue"); axes[0].set_xlabel("K_ii (cm$^{-1}$)"); axes[0].set_title("Figure 1a. Per-mode first-order shifts")
axes[1].hist(np.log10(np.abs(off) + 1e-3), bins=60, color="darkorange"); axes[1].set_xlabel("log10 |K_ij| (cm$^{-1}$)"); axes[1].set_title("Figure 1b. Couplings")
plt.tight_layout(); fig.savefig(FIG / "fig1_targets.png", dpi=140); plt.show()""")
md("""*Preprocessing considerations.* Sequences have different lengths, so molecules are padded to the longest one and a mask keeps padding
out of attention, loss and metrics. Targets are in cm⁻¹ and are not standardised: the loss is a plain squared error over the filled family-block
elements, so a 1 cm⁻¹ error means the same thing everywhere. Splits are **by molecule** (a hash of the identifier: 80 % train, 10 %
validation, 10 % test), never by mode, because the modes of one molecule are strongly correlated.""")
code("""def split_of(mol_id):
    h = int(hashlib.sha1(mol_id.encode()).hexdigest(), 16) % 10
    return "test" if h == 0 else ("val" if h == 1 else "train")
split = np.array([split_of(s) for s in ids])
idx = {s: np.where(split == s)[0] for s in ("train", "val", "test")}
print({s: len(v) for s, v in idx.items()})
T = dict(tokens=torch.tensor(tokens), family=torch.tensor(family).clamp_min(0), mask=torch.tensor(mask), K=torch.tensor(K),
         charge=torch.tensor(z["charge"]).long(), mult=torch.tensor(z["mult"]).long(), omega=torch.tensor(omega))""")

md("""## 2. Baseline model (PyTorch)

The ΔH model (design sheet `architecture/50_deltaH_model_components.mmd`, code `m05/deltah_model.py`): a **token embedding** (a linear layer
with GELU and LayerNorm on the 23 mode features, plus two learned molecule tokens for charge and spin multiplicity, so that cations can join
later without a change of architecture), an **encoder-only Transformer backbone** (2 layers, 4 heads, width 64, feed-forward 256, dropout 0.1,
pre-norm), and two output heads on the contextualised mode vectors: the **block head** reads the pair of vectors (i, j) together with their
frequencies and writes K_ij, applied to every pair inside a family; the **pair head** writes a logit for "this pair carries a large correction".

*Why a Transformer.* The input is a set of variable length whose elements interact through pairs (a coupling is a statement about two
modes at once); self-attention is permutation-aware and sees every pair in one layer. A recurrent network would impose an order the
modes do not have; a convolution would impose locality in frequency that couplings do not respect. *Why small.* The corpus is hundreds of
molecules, not millions; the design keeps 136 k parameters and relies on the physics in the tokens rather than on capacity.""")
code("""cfg = DeltaHConfig(n_families=4, n_irreps=0, n_env=13, n_layers=2)    # n_env 13 = 12 environment classes + the out-of-plane share
model = DeltaHModel(cfg); assert cfg.d_in == D, (cfg.d_in, D)
print(model); print("parameters:", f"{model.n_parameters():,}")""")

md("""## 3. Training

Loss = block loss (mean squared error over the filled family-block elements; the block rule of 19 September) + the pair head's binary
cross-entropy with the positive class weighted by its rarity. AdamW (lr 1e-3, weight decay 1e-2), batches of 8 molecules, early stopping on
the validation loss, three seeds. Training progress is shown as loss curves.""")
code("""def batches(ix, bs, rng=None):
    ix = np.array(ix);
    if rng is not None: rng.shuffle(ix)
    for s in range(0, len(ix), bs): yield ix[s:s + bs]

def pair_labels(Kb, maskb):
    scale = (torch.diagonal(Kb, dim1=1, dim2=2).abs() * maskb).amax(1)                      # max_k |K_kk| per molecule
    lab = (Kb.abs() >= THETA * scale[:, None, None]).float()
    eye = torch.eye(Kb.shape[1], dtype=torch.bool)[None]
    valid = maskb[:, :, None] & maskb[:, None, :] & ~eye
    return lab, valid

def losses(m, b):
    out = m(T["tokens"][b], T["family"][b], T["charge"][b], T["mult"][b], T["mask"][b])
    lb = block_loss(out["block"], T["K"][b], T["family"][b], T["mask"][b])
    lab, valid = pair_labels(T["K"][b], T["mask"][b])
    pos = lab[valid].mean().clamp(1e-3, 0.5); w = torch.where(lab > 0, (1 - pos) / pos, torch.ones_like(lab))
    lp = (nn.functional.binary_cross_entropy_with_logits(out["pair_logits"], lab, weight=w, reduction="none") * valid).sum() / valid.sum().clamp_min(1)
    return lb, lp, out

def train(cfg, seed, epochs=EPOCHS, bs=8, patience=6):
    torch.manual_seed(seed); rng = np.random.default_rng(seed)
    m = DeltaHModel(cfg); opt = torch.optim.AdamW(m.parameters(), lr=cfg.lr, weight_decay=cfg.weight_decay)
    hist = {"train": [], "val": []}; best = (float("inf"), None, 0)
    for ep in range(epochs):
        m.train(); tl = []
        for b in batches(idx["train"], bs, rng):
            lb, lp, _ = losses(m, torch.tensor(b)); loss = lb + lp
            opt.zero_grad(); loss.backward(); nn.utils.clip_grad_norm_(m.parameters(), 1.0); opt.step(); tl.append(float(loss))
        m.eval()
        with torch.no_grad():
            lb, lp, _ = losses(m, torch.tensor(idx["val"])); vl = float(lb + lp)
        hist["train"].append(float(np.mean(tl))); hist["val"].append(vl)
        if vl < best[0] - 1e-4: best = (vl, {k: v.clone() for k, v in m.state_dict().items()}, ep)
        elif ep - best[2] >= patience: break
    m.load_state_dict(best[1]); m.eval()
    return m, hist, best[2]

t0 = time.time(); runs = {"baseline": [train(cfg, s) for s in SEEDS]}
print(f"baseline: {len(SEEDS)} seed(s), best epochs {[r[2] for r in runs['baseline']]}, {time.time() - t0:.0f} s")""")
code("""def plot_curves(runs, name, fname):
    fig, ax = plt.subplots(figsize=(6, 3.4))
    for k, (m, h, be) in enumerate(runs):
        ax.plot(h["train"], color="steelblue", alpha=0.6, label="train" if k == 0 else None); ax.plot(h["val"], color="darkorange", alpha=0.8, label="validation" if k == 0 else None)
    ax.set_xlabel("epoch"); ax.set_ylabel("loss (block MSE + pair BCE)"); ax.set_title(f"{fname}. {name}: loss per epoch, {len(runs)} seed(s)"); ax.legend(); plt.tight_layout()
    fig.savefig(FIG / f"{fname.lower().replace(' ', '')}_{name}.png", dpi=140); plt.show()
plot_curves(runs["baseline"], "baseline", "Figure 2")""")

md("""## 4. Controlled comparison: one change

**What changed:** the depth of the backbone, 2 → 4 encoder layers. **Everything else is identical:** tokens, heads, width, dropout, optimiser,
learning rate, batch size, epochs, early-stopping rule, splits and seeds. **Why this change:** the block target couples every mode of a family
with every other; one attention layer sees pairs, two layers see pairs of pairs. If the corrections are governed by longer chains of
interaction (a substituent changing a ring mode changing a C–H bend), depth should help; if the tokens already carry what matters, the deeper
model should only overfit on a corpus of this size. Either outcome is informative for the pipeline's design (recipe, controlled change).""")
code("""cfg4 = DeltaHConfig(n_families=4, n_irreps=0, n_env=13, n_layers=4)
t0 = time.time(); runs["4 layers"] = [train(cfg4, s) for s in SEEDS]
print(f"4 layers: parameters {DeltaHModel(cfg4).n_parameters():,} (baseline {model.n_parameters():,}); best epochs {[r[2] for r in runs['4 layers']]}, {time.time() - t0:.0f} s")
plot_curves(runs["4 layers"], "4layers", "Figure 3")""")

md("""## 5. Evaluation and comparison

Metrics fit for the task, on the held-out test molecules. **Block head:** root-mean-square error of the predicted family-block elements in
cm⁻¹, per family and separately for the diagonal (band shifts) and the couplings, against two rules that need no learning — the *zero rule*
(no correction) and the *family-median rule* (each mode gets the training-set median shift of its family, couplings zero). **Pair head:**
average precision of the support prediction against the *resonance-denominator rule* of the recipe (score 1/|ω_i² − ω_j²| within a family),
so the learned head has to beat a free physical rule, not chance.""")
code("""def average_precision(score, label):
    o = np.argsort(-score); l = label[o];
    if l.sum() == 0: return float("nan")
    prec = np.cumsum(l) / (np.arange(len(l)) + 1); return float((prec * l).sum() / l.sum())

def evaluate(models, ix):
    b = torch.tensor(ix); res = {F: {"diag": [], "coup": []} for F in FAMILIES}; ap_model = []
    fam = T["family"][b]; mk = T["mask"][b]; Kt = T["K"][b]
    same = (fam[:, :, None] == fam[:, None, :]) & mk[:, :, None] & mk[:, None, :]
    eye = torch.eye(Kt.shape[1], dtype=torch.bool)[None]
    with torch.no_grad():
        preds = torch.stack([m(T["tokens"][b], fam, T["charge"][b], T["mult"][b], mk)["block"] for m, _, _ in models]).mean(0)
        logits = torch.stack([m(T["tokens"][b], fam, T["charge"][b], T["mult"][b], mk)["pair_logits"] for m, _, _ in models]).mean(0)
    err = (preds - Kt)
    for k, F in enumerate(FAMILIES):
        inF = same & (fam[:, :, None] == k)
        d = err[inF & eye]; c = err[inF & ~eye]
        res[F]["diag"] = float(d.pow(2).mean().sqrt()) if d.numel() else float("nan"); res[F]["coup"] = float(c.pow(2).mean().sqrt()) if c.numel() else float("nan")
    lab, valid = pair_labels(Kt, mk)
    ap = average_precision(logits[valid].numpy(), lab[valid].numpy())
    return res, ap

def rules(ix):
    b = torch.tensor(ix); fam = T["family"][b]; mk = T["mask"][b]; Kt = T["K"][b]; om = T["omega"][b]
    same = (fam[:, :, None] == fam[:, None, :]) & mk[:, :, None] & mk[:, None, :]; eye = torch.eye(Kt.shape[1], dtype=torch.bool)[None]
    tr = torch.tensor(idx["train"]); med = {}
    for k in range(len(FAMILIES)):
        dtr = torch.diagonal(T["K"][tr], dim1=1, dim2=2)[(T["family"][tr] == k) & T["mask"][tr]]
        med[k] = float(dtr.median()) if dtr.numel() else 0.0
    out = {"zero": {}, "family-median": {}}
    for k, F in enumerate(FAMILIES):
        inF = same & (fam[:, :, None] == k)
        dz = Kt[inF & eye]; cz = Kt[inF & ~eye]
        out["zero"][F] = {"diag": float(dz.pow(2).mean().sqrt()) if dz.numel() else float("nan"), "coup": float(cz.pow(2).mean().sqrt()) if cz.numel() else float("nan")}
        dm = Kt[inF & eye] - med[k]
        out["family-median"][F] = {"diag": float(dm.pow(2).mean().sqrt()) if dm.numel() else float("nan"), "coup": out["zero"][F]["coup"]}
    lab, valid = pair_labels(Kt, mk)
    w2 = om.pow(2); score = 1.0 / (w2[:, :, None] - w2[:, None, :]).abs().clamp_min(1.0); score = torch.where(same, score, torch.zeros_like(score))
    return out, average_precision(score[valid].numpy(), lab[valid].numpy())

rule_rms, ap_rule = rules(idx["test"])
table = []; aps = {}
for name, ms in runs.items():
    r, ap = evaluate(ms, idx["test"])
    for F in FAMILIES: table.append(dict(model=name, family=F, rms_diag=r[F]["diag"], rms_coup=r[F]["coup"]))
    print(f"{name}: pair-head average precision {ap:.3f} (resonance rule {ap_rule:.3f})"); aps[name] = ap
for rule in ("zero", "family-median"):
    for F in FAMILIES: table.append(dict(model=rule, family=F, rms_diag=rule_rms[rule][F]["diag"], rms_coup=rule_rms[rule][F]["coup"]))
tab = pd.DataFrame(table).pivot(index="family", columns="model", values=["rms_diag", "rms_coup"]).round(2)
tab""")
code("""fig, axes = plt.subplots(1, 2, figsize=(11, 3.6))
for ax, what, title in ((axes[0], "rms_diag", "Figure 4a. Band shifts (diagonal): RMS error, cm$^{-1}$"), (axes[1], "rms_coup", "Figure 4b. Couplings: RMS error, cm$^{-1}$")):
    sub = tab[what][["zero", "family-median", "baseline", "4 layers"]]; sub.plot.bar(ax=ax, width=0.8); ax.set_title(title); ax.set_ylabel("cm$^{-1}$"); ax.tick_params(axis="x", rotation=0)
plt.tight_layout(); fig.savefig(FIG / "fig4_test_errors.png", dpi=140); plt.show()
results = dict(release=RELEASE.name, n_molecules=int(N), n_modes_total=int(mask.sum()), splits={s: int(len(v)) for s, v in idx.items()}, quick=QUICK, epochs=EPOCHS, seeds=SEEDS,
               parameters={"baseline": model.n_parameters(), "4 layers": DeltaHModel(cfg4).n_parameters()}, best_epochs={k: [r[2] for r in v] for k, v in runs.items()},
               test_rms={F: {m_: {"diag": float(tab["rms_diag"].loc[F, m_]), "coup": float(tab["rms_coup"].loc[F, m_])} for m_ in ("zero", "family-median", "baseline", "4 layers")} for F in FAMILIES},
               pair_ap={"baseline": aps["baseline"], "4 layers": aps["4 layers"], "resonance-rule": ap_rule}, final_val_loss={k: [r[1]["val"][r[2]] for r in v] for k, v in runs.items()})
json.dump(results, open("results.json", "w"), indent=1); print("results.json written")""")

# ---- summary: from results.json when it exists (a previous execution), else a placeholder that says so
res_path = HERE / "results.json"
if res_path.exists():
    R = json.load(open(res_path, encoding="utf-8"))
    rip = R["test_rms"]["ring-ip"]; oop = R["test_rms"]["CH-oop"]
    better = "the deeper model" if np.nanmean([R["test_rms"][F]["4 layers"]["diag"] for F in R["test_rms"]]) < np.nanmean([R["test_rms"][F]["baseline"]["diag"] for F in R["test_rms"]]) else "the baseline"
    summary = (f"""## 6. Summary

The task was to predict, from cheap-level normal-mode tokens alone, the family blocks of the correction matrix between two levels of
theory for {R['n_molecules']} molecules ({R['n_modes_total']:,} modes; release `{R['release']}`), split by molecule into
{R['splits']['train']}/{R['splits']['val']}/{R['splits']['test']}. The baseline was the ΔH model with a two-layer encoder ({R['parameters']['baseline']:,}
parameters); the one controlled change was depth, four layers ({R['parameters']['4 layers']:,} parameters), everything else fixed, {len(R['seeds'])} seed(s).
On the test molecules the ring-in-plane band shifts came out at RMS {rip['baseline']['diag']:.1f} cm⁻¹ (baseline) and {rip['4 layers']['diag']:.1f} (four layers) against
{rip['zero']['diag']:.1f} for the zero rule and {rip['family-median']['diag']:.1f} for the family-median rule; the C–H out-of-plane shifts {oop['baseline']['diag']:.1f} / {oop['4 layers']['diag']:.1f}
against {oop['zero']['diag']:.1f} / {oop['family-median']['diag']:.1f}; the pair head reached average precision {R['pair_ap']['baseline']:.2f} / {R['pair_ap']['4 layers']:.2f} against
{R['pair_ap']['resonance-rule']:.2f} for the resonance-denominator rule. The most important difference between the two configurations is therefore
{('small' if abs(rip['baseline']['diag'] - rip['4 layers']['diag']) < 1.0 else 'in favour of ' + better)} on this corpus. The unexpected part is recorded with the numbers above; """
               + ("this was a quick pipeline check (fewer epochs, one seed) and not a result." if R.get("quick") else "the comparison stands as pre-registered."))
else:
    summary = ("## 6. Summary\n\n*Written from `results.json` after the first full execution (the builder fills this section from the recorded numbers); "
               "not yet executed.*")
md(summary)

# ---- 7. follow-up cells (23 September 2026): kept *after* the original run so that the change of understanding stays visible
md("""## 7. Follow-up (23 September 2026): a corrupted target found by a second route, and what the couplings needed

*Added after the first full run; sections 1–6 are unchanged, so a reader can see what was learned and from what. Everything below runs in the
same environment and with the same split.*

Two things happened after section 6, both outside this notebook and both recorded in the project's pre-registrations (E6 of 19 September, E7 of
23 September). **First**, a learning curve on the same corpus showed that the couplings — the off-diagonal elements of the family block — were
not learned by the model above at any data size (their error equals the zero rule to two decimals in Table 1 above), and the cause was traced to
the target, not to the network: in the normal-mode basis K_ij changes sign when one mode vector is flipped, and every per-mode token is a square of
that vector, so a least-squares model on these tokens has its optimum at exactly zero. In a local pairwise force-constant representation the same
corpus does teach the couplings; the numbers are shown in 7.3 for comparison. **Second**, one molecule's target was simply wrong: benzene's ωB97X
Hessian from finite differences disagreed with an analytic second calculation at the same geometry by up to 133 cm⁻¹. The corpus was screened,
the one molecule was replaced by its second route, and the baseline is retrained below with nothing else changed.""")
code("""import os
SR = Path("..") / "data" / "second_route"
chk = json.load(open(SR / "benzene_analytic_check.json", encoding="utf-8"))
screen = json.load(open(SR / "corpus_screen_2026-09-23.json", encoding="utf-8"))
fa = np.array(chk["wb97x"]["freq_analytic"]); fc = np.array(chk["wb97x"]["freq_corpus"])
print("benzene, ωB97X at the B3LYP geometry — analytic (pyscf) vs corpus finite differences (psi4), the ten largest disagreements (cm⁻¹):")
order = np.argsort(-np.abs(fa - fc))[:10]
display(pd.DataFrame({"analytic": fa[order].round(0), "corpus FD": fc[order].round(0), "difference": (fa - fc)[order].round(0)}).sort_values("analytic").reset_index(drop=True))
print(f"|H_analytic − H_corpus|: ωB97X max {chk['wb97x']['dH_max']:.1e} a.u., B3LYP max {chk['b3lyp']['dH_max']:.1e} a.u.")
sc = pd.DataFrame(screen["rows"]).sort_values("max_abs_shift", ascending=False)
print(f"\\ncorpus screen: max |ω(ωB97X) − ω(B3LYP)| over sorted frequency lists, {len(sc)} molecules — median {sc['max_abs_shift'].median():.0f} cm⁻¹; "
      f"molecules above 100: {(sc['max_abs_shift'] > 100).sum()}")
display(sc.head(6).reset_index(drop=True))""")
md("""*Reading.* At a geometry that is D6h to 10⁻⁴ Å, degenerate pairs must be degenerate; the corpus Hessian splits them (563/605, 1223/1343) and the
analytic one does not (625/625, 1210/1210). The "+151 cm⁻¹ ring shift" in benzene's target was an artefact of the finite-difference Hessian. The
screen shows benzene as the only molecule above 100 cm⁻¹; the corpus is sound apart from it. The lesson is the project's noise principle: every
derived quantity gets a second route before it is trusted.""")
code("""RELEASE_B = Path("..") / "data" / "corpus_release" / (os.environ.get("M05_RELEASE_FOLLOWUP", "layerA2_2026-09-23b") + ".npz")
zb = np.load(RELEASE_B); man_b = json.load(open(str(RELEASE_B).replace(".npz", "_manifest.json")))
print("follow-up release:", RELEASE_B.name, "| molecules:", len(zb["ids"]), "| second-route Hessians for:", man_b.get("analytic_second_route"))
assert list(zb["ids"]) == list(ids), "the follow-up release must contain the same molecules in the same order"
split_b = np.array([split_of(s) for s in zb["ids"]]); idx_b = {s: np.where(split_b == s)[0] for s in ("train", "val", "test")}
bz = [k for k, s in enumerate(ids) if s == "A_8448043181"]
print("benzene is in the", split_b[bz[0]] if bz else "—", "split")
T_b = dict(tokens=torch.tensor(zb["tokens"]), family=torch.tensor(zb["family"]).clamp_min(0), mask=torch.tensor(zb["mask"]), K=torch.tensor(zb["K"]),
           charge=torch.tensor(zb["charge"]).long(), mult=torch.tensor(zb["mult"]).long(), omega=torch.tensor(zb["omega_cm"]))
# retrain the baseline on the corrected release with the identical protocol; the functions above read the globals T and idx, so swap them for the duration
T_v1, idx_v1 = T, idx
T, idx = T_b, idx_b
t0 = time.time(); runs_b = {"baseline (corrected release)": [train(cfg, s) for s in SEEDS]}
print(f"retrained: best epochs {[r[2] for r in runs_b['baseline (corrected release)']]}, {time.time() - t0:.0f} s")
rule_b, ap_rule_b = rules(idx["test"]); r_b, ap_b = evaluate(runs_b["baseline (corrected release)"], idx["test"])
T, idx = T_v1, idx_v1
rows = []
for F in FAMILIES:
    rows.append(dict(family=F, **{"zero (v1)": tab["rms_diag"].loc[F, "zero"], "baseline v1 (section 3)": tab["rms_diag"].loc[F, "baseline"],
                                  "zero (corrected)": rule_b["zero"][F]["diag"], "baseline retrained (corrected)": r_b[F]["diag"]}))
tab_b = pd.DataFrame(rows).set_index("family").round(2)
print("band shifts (diagonal), test RMS in cm⁻¹ — the original run beside the retrained baseline on the corrected release:"); display(tab_b)
print(f"pair-head average precision: v1 {aps['baseline']:.3f} → corrected {ap_b:.3f} (resonance rule {ap_rule_b:.3f})")""")
md("""*Reading.* The retrained numbers move little: benzene is one molecule, and the diagonal was never the problem. The table is here because a reader
must be able to see that correcting one target did not rewrite the result — and because the same second route would have caught the artefact
before the first run, had it been in place.""")
code("""E7 = Path("..") / "out" / "E7_rungB_2026-09-23_analytic.json"
E6 = Path("..") / "out" / "E6_learning_curve_in_data_2026-09-23_excl_imaginary.json"
followup = dict(release_followup=RELEASE_B.name, analytic_second_route=man_b.get("analytic_second_route"), benzene_split=(split_b[bz[0]] if bz else None),
                test_rms_diag_corrected={F: {"zero": float(rule_b["zero"][F]["diag"]), "baseline_retrained": float(r_b[F]["diag"])} for F in FAMILIES},
                test_rms_coup_corrected={F: {"zero": float(rule_b["zero"][F]["coup"]), "baseline_retrained": float(r_b[F]["coup"])} for F in FAMILIES},
                pair_ap_corrected=float(ap_b), benzene_check=dict(wb97x_dH_max=chk["wb97x"]["dH_max"], max_freq_disagreement_cm=float(np.abs(fa - fc).max())),
                screen=dict(n=int(len(sc)), median_max_shift=float(sc["max_abs_shift"].median()), above_100=int((sc["max_abs_shift"] > 100).sum())))
if E7.exists() and E6.exists():
    e7 = json.load(open(E7, encoding="utf-8")); e6 = json.load(open(E6, encoding="utf-8")); nf = str(e7["sizes"][-1])
    cmp = pd.DataFrame({"training molecules": e7["sizes"],
                        "mode basis, block model (E6, hold-out a)": [e6["curve"][str(n)]["M2"]["mean"]["a"]["coupling_ratio"] for n in e6["sizes"]],
                        "local pairs, MLP (E7, hold-out a)": e7["readings"]["coupling_ratio_curve_mlp"]["a"],
                        "local pairs, MLP (E7, hold-out b: unseen cores)": e7["readings"]["coupling_ratio_curve_mlp"]["b"]}).round(2)
    print("ring coupling RMS / zero-rule RMS (1.00 = predicting no coupling), from the pre-registered curves E6 and E7:"); display(cmp)
    ma, mb = e7["curve"][nf]["B1_mlp"]["mean"]["a"], e7["curve"][nf]["B1_mlp"]["mean"]["b"]
    print(f"corrected-frequency RMS with the local pairwise model at {nf} molecules: hold-out (a) {ma['corrected_freq_rms']:.1f} cm⁻¹ (zero rule {ma['corrected_freq_rms_zero_rule']:.1f}), "
          f"hold-out (b) {mb['corrected_freq_rms']:.1f} ({mb['corrected_freq_rms_zero_rule']:.1f})")
    followup["e7"] = dict(sizes=e7["sizes"], ratio_a=e7["readings"]["coupling_ratio_curve_mlp"]["a"], ratio_b=e7["readings"]["coupling_ratio_curve_mlp"]["b"],
                          corrected_freq_rms_a=ma["corrected_freq_rms"], corrected_freq_rms_b=mb["corrected_freq_rms"], zero_rule_a=ma["corrected_freq_rms_zero_rule"], zero_rule_b=mb["corrected_freq_rms_zero_rule"])
else:
    print("E6/E7 result files not present in this checkout; the comparison is in the project notes.")
json.dump(followup, open("results_followup.json", "w"), indent=1); print("results_followup.json written")""")
md("""### 7.4 What we learned

- **A target can be wrong, and a model will faithfully fail on it.** One finite-difference Hessian out of 244 carried a 133 cm⁻¹ artefact; it sat in
  a held-out set and looked like a learning failure for a day. A second, independent route for every derived quantity is now part of the corpus
  check, not a thing done afterwards.
- **The network was never the limit; the representation was.** Asked for a sign-ambiguous, basis-dependent object, the model above learned the only
  thing consistent with its inputs — zero couplings — and no amount of data changed that (flat curve, E6). Asked for the local, chemically named object
  the correction actually is (bond–bond interaction constants inside rings, pairs of internals sharing an atom), the same 175 molecules taught the
  couplings on molecules of cores never seen in training (E7). The model of sections 2–5 is kept as the pre-registered baseline of this module; the
  next version of the module would put the pairwise local target in its place.
- **Pre-registration made both findings legible.** The predictions, the win/lose rules and the outcomes — including the ones that lost — are in the
  project's notes with dates, so the reader can tell what was expected from what was found.""")

md("""## 8. Follow-up (24 September 2026): the imaginary-mode molecules read along the second route, and what the coupled-cluster correction needs

Section 7 replaced one corrupted target and retrained. The day after, the same second route (analytic pyscf Hessians at the corpus geometry,
grid 99/590) was run for **every** molecule the release rule had dropped for an imaginary mode — twenty — and a coupled-cluster Hessian of benzene
(CCSD(T)/cc-pVDZ, 72 gradients) was read with the projections of E7 to see whether the *real* correction lives where the DFT proxy's does. Both
change what this module should say about its data and its target, so both are added here as follow-up cells; sections 1–7 stand as run.""")
md("""### 8.1 Twenty imaginary modes: five were the deck's noise, fifteen are real""")
code("""SR2 = Path("..") / "data" / "second_route" / "imaginary_second_route_2026-09-24.json"
imag = json.load(open(SR2, encoding="utf-8"))
rows = []
for r in imag["rows"]:
    if r.get("status") != "ok":
        continue
    f = r["functionals"]
    rows.append(dict(molecule=r["name"], **{"B3LYP corpus → analytic": f"{f['b3lyp']['corpus_lowest']} → {f['b3lyp']['analytic_lowest']}",
                                          "ωB97X corpus → analytic": f"{f['wb97x']['corpus_lowest']} → {f['wb97x']['analytic_lowest']}",
                                          "verdict": r["molecule_verdict"].split(" — ")[0]}))
imag_tab = pd.DataFrame(rows)
n_heal = sum(r["verdict"].startswith("healed") for r in rows); n_gen = sum(r["verdict"].startswith("genuine") for r in rows)
print(f"{len(rows)} molecules read along the second route: {n_heal} healed (the finite-difference deck flipped a soft torsion), {n_gen} genuine imaginary modes")
display(imag_tab[imag_tab["verdict"] != "no imaginary mode in the corpus"].reset_index(drop=True))""")
md("""*Reading.* The four ωB97X-only flips all heal — the range-separated functional on psi4's default grid, the same mechanism as benzene's 133 cm⁻¹
artefact — and one B3LYP case heals too. The twelve B3LYP-only cases do not: the analytic Hessian agrees, to a few cm⁻¹, that the substituent
torsion (NO2, CF3, vinyl, Cl) is imaginary, so those geometries are saddle points of the optimiser, a *geometry* fault rather than a Hessian
one, to be fixed by re-optimising from a twisted start. The release rule of section 1 ("drop imaginary-mode molecules") was therefore right for
fifteen and wrong for five; the release builder now reads the rule from the analytic frequencies when a second route exists.""")
md("""### 8.2 The baseline retrained on the 229-molecule release""")
code("""# the v1 numbers come from results.json and results_followup.json (written by sections 5 and 7), so this section can also run append-only
# in a kernel that did not retrain sections 3–5 (execute_section8.py; the trained models of those sections are not needed here)
r_v1 = json.load(open("results.json", encoding="utf-8")); followup = json.load(open("results_followup.json", encoding="utf-8"))
RELEASE_C = Path("..") / "data" / "corpus_release" / (os.environ.get("M05_RELEASE_FOLLOWUP2", "layerA2_2026-09-24") + ".npz")
zc = np.load(RELEASE_C); man_c = json.load(open(str(RELEASE_C).replace(".npz", "_manifest.json")))
new_ids = [s for s in zc["ids"] if s not in set(ids)]
print("release:", RELEASE_C.name, "| molecules:", len(zc["ids"]), "| new since section 7:", len(new_ids), "| analytic second route for:", len(man_c.get("analytic_second_route", [])), "molecules")
split_c = np.array([split_of(s) for s in zc["ids"]]); idx_c = {s: np.where(split_c == s)[0] for s in ("train", "val", "test")}
print("splits by the same sha rule:", {s: int(len(v)) for s, v in idx_c.items()}, "| the five new molecules fall into:", [split_of(s) for s in new_ids])
T_c = dict(tokens=torch.tensor(zc["tokens"]), family=torch.tensor(zc["family"]).clamp_min(0), mask=torch.tensor(zc["mask"]), K=torch.tensor(zc["K"]),
           charge=torch.tensor(zc["charge"]).long(), mult=torch.tensor(zc["mult"]).long(), omega=torch.tensor(zc["omega_cm"]))
T_v1, idx_v1 = T, idx
T, idx = T_c, idx_c
t0 = time.time(); runs_c = {"baseline (229-molecule release)": [train(cfg, s) for s in SEEDS]}
print(f"retrained: best epochs {[r[2] for r in runs_c['baseline (229-molecule release)']]}, {time.time() - t0:.0f} s")
rule_c, ap_rule_c = rules(idx["test"]); r_c, ap_c = evaluate(runs_c["baseline (229-molecule release)"], idx["test"])
T, idx = T_v1, idx_v1
rows = []
for F in FAMILIES:
    rows.append(dict(family=F, **{"zero (v1)": r_v1["test_rms"][F]["zero"]["diag"], "baseline v1 (section 3)": r_v1["test_rms"][F]["baseline"]["diag"],
                                  "baseline retrained (7.2, 224)": followup["test_rms_diag_corrected"][F]["baseline_retrained"],
                                  "zero (229)": rule_c["zero"][F]["diag"], "baseline retrained (229)": r_c[F]["diag"]}))
tab_c = pd.DataFrame(rows).set_index("family").round(2)
print("band shifts (diagonal), test RMS in cm⁻¹ — v1, the 224-molecule retrain of 7.2, and the 229-molecule retrain:"); display(tab_c)
print(f"pair-head average precision: v1 {r_v1['pair_ap']['baseline']:.3f} → 224 {followup['pair_ap_corrected']:.3f} → 229 {ap_c:.3f} (resonance rule {ap_rule_c:.3f})")""")
md("""*Reading.* Five molecules more, all of them with a soft torsion that is now real; the test set changes only by whichever of them the sha rule
sends there, so the numbers are comparable within the seed scatter of section 3. The point of the cell is the same as 7.2's: the reader sees
that a data correction did not rewrite the result, and that the rule which drops molecules is now evidence-based per molecule.""")
md("""### 8.3 E8: does the coupled-cluster correction live where the proxy's does?""")
code("""E8D = Path("..") / ".." / ".." / "probes" / "results_m1" / "e8_benzene_ccpvdz"
e8 = json.load(open(E8D / "E8_locality_benzene.json", encoding="utf-8")); e8b = json.load(open(E8D / "E8_between_benzene.json", encoding="utf-8"))
rows = []
for pname, d in e8["patterns"].items():
    for corr, r in d.items():
        rows.append(dict(pattern=pname, correction=corr, **{"ΔH residual ratio": round(r["dH_residual_ratio"], 2), "ring coupling ratio": round(r["ring_coupling_ratio"], 2),
                                                          "corrected ω RMS (cm⁻¹)": round(r["corrected_freq_rms"], 1), "zero rule (cm⁻¹)": round(r["corrected_freq_rms_zero_rule"], 1)}))
for pname in ("(d) (c) + pairs two bonds apart",):
    for corr in ("CC − B3LYP", "proxy ωB97X − B3LYP"):
        r = e8b["patterns"][pname][f"{corr} | mask"]
        rows.append(dict(pattern=pname, correction=corr, **{"ΔH residual ratio": round(r["dH_residual_ratio"], 2), "ring coupling ratio": round(r["ring_coupling_ratio"], 2),
                                                          "corrected ω RMS (cm⁻¹)": round(r["corrected_freq_rms"], 1), "zero rule (cm⁻¹)": round(r["corrected_freq_rms_zero_rule"], 1)}))
e8_tab = pd.DataFrame(rows)
print("benzene, CCSD(T)/cc-pVDZ − B3LYP (the real correction) beside the DFT proxy, read by the parameter-free projections of E7 (masked minimum-norm ΔF):")
display(e8_tab)
print(f"verdict by the pre-registered rule: {e8['verdict']}; exploratory correlation of the CC and proxy ΔF on pattern (c): {e8['exploratory']['corr_CC_vs_proxy_on_pattern_c']:.2f}")""")
md("""*Reading.* The real correction is *more* local than the proxy in norm — 92 % of it sits in the pattern of section 7 (diagonal, pairs sharing an
atom, bond–bond pairs in a ring) and 98 % once pairs two bonds apart are added — but its ring couplings need that extra class: 0.80 with the
section-7 pattern, 0.34 with pairs two bonds apart, against 0.15 for the proxy already at the smaller pattern. In words: the DFT proxy's
couplings are nearest-neighbour, the coupled-cluster correction reaches one bond further. For the pairwise local model this is one more pair class
in the mask (the feature "ring-path distance 2" already exists); for this module's mode-basis baseline it changes nothing, which is itself the
finding — the mode basis cannot express any of this. One molecule; naphthalene (two rings, D2h) is being computed to read transfer between cores.""")
md("""### 8.4 What we learned (continued)

- **A data-quality rule should be evidence per molecule, not a blanket.** "Drop imaginary modes" removed five good molecules with the fifteen bad
  ones; a second route per flagged molecule tells them apart in minutes of compute.
- **The noisier route is the range-separated functional.** Every ωB97X-only flip healed; on the real modes the deck's finite differences disagree with
  the analytic Hessian by up to 32 cm⁻¹ for ωB97X and 6 for B3LYP. New corpus layers use analytic Hessians.
- **The real target is local like the proxy, one bond further.** E8 is the first measurement of the coupled-cluster correction itself; it confirms the
  representation of section 7 and sharpens it by one pair class. The module's next version predicts that object; this version's baseline stays as the
  pre-registered comparison point.""")
code("""followup2 = dict(release_followup2=RELEASE_C.name, n_molecules=int(len(zc["ids"])), new_ids=new_ids,
                 imaginary_second_route=dict(n_read=len(imag_tab), healed=int(n_heal), genuine=int(n_gen)),
                 test_rms_diag_229={F: {"zero": float(rule_c["zero"][F]["diag"]), "baseline_retrained": float(r_c[F]["diag"])} for F in FAMILIES},
                 pair_ap_229=float(ap_c), splits_229={s: int(len(v)) for s, v in idx_c.items()},
                 e8=dict(verdict=e8["verdict"], pattern_c_cc=e8["patterns"]["(c) + ring bond-bond pairs"]["CC − B3LYP"],
                         pattern_d_cc_mask=e8b["patterns"]["(d) (c) + pairs two bonds apart"]["CC − B3LYP | mask"],
                         pattern_c_proxy=e8["patterns"]["(c) + ring bond-bond pairs"]["proxy ωB97X − B3LYP"]))
json.dump(followup2, open("results_followup2.json", "w"), indent=1); print("results_followup2.json written")""")

md("""## 9. Follow-up (25 September 2026): how far the correction carries — across a molecule, across molecules, across size

Section 8 read the coupled-cluster correction as local, one bond further than the proxy. The next day three pre-registered tests asked what that
locality buys: whether a substituted molecule's correction can be built from its parent core plus a probed neighbourhood (E9), whether that
neighbourhood block can be measured once, on the smallest host, and transplanted (E10), and whether a model trained on small molecules predicts
larger ones (a size-extrapolation split of section 7's pair model). None of them retrains this module's baseline; all read files already on disk,
so they run append-only here. The reading rules were written before the numbers (`GoalGathering/notes/PreRegistration_2026-09-24_E9_*`,
`..._E10_*`, `..._2026-09-25_Size_Extrapolation_*`).""")
md("""### 9.1 E9 — transfer the core, probe the substituent""")
code("""E9D = Path("..") / "data" / "e9"
e9 = json.load(open(E9D / "e9_core_transfer_2026-09-24.json", encoding="utf-8")); e9p = json.load(open(E9D / "e9_posthoc_block_2026-09-24.json", encoding="utf-8"))
rows = []
for r in e9["radii"]:
    for k, label in (("transfer_probe", "core block + probed columns (the claim)"), ("probe_only", "probed columns only"), ("transfer_only", "core block only")):
        v = e9["variants"][f"{k}_r{r}"]
        rows.append(dict(r=r, variant=label, **{"columns probed": round(v["column_fraction_mean"], 2), "ΔH residual ratio": round(v["dH_residual_ratio"], 3),
                                                 "ring coupling ratio": round(v["coupling_ratio"], 2), "corrected ω RMS (cm⁻¹)": round(v["corrected_freq_rms"], 2)}))
e9_tab = pd.DataFrame(rows)
print(f"{e9['n_admitted']} substituted molecules, {len(e9['skipped'])} skipped; zero rule {e9['variants']['zero']['corrected_freq_rms']:.1f} cm⁻¹; registered verdict at r = 2: {e9['verdict_r2']}")
display(e9_tab[e9_tab.r.isin([0, 2, 4])].reset_index(drop=True))
d2 = e9p["variants"]["d_block_plus_core_couplings_r2"]; e2 = e9p["variants"]["e_block_only_far_core_r2"]
print(f"energy-only variant (post-hoc): near×near block probed + the core's couplings → {d2['corrected_freq_rms']:.2f} cm⁻¹ (ratio {d2['coupling_ratio']:.2f}); without the core's near×far couplings {e2['corrected_freq_rms']:.2f}")
fig, ax = plt.subplots(figsize=(5.5, 3.4))
for k, label, mk in (("transfer_probe", "core block + probed columns", "o"), ("probe_only", "probed columns only", "s"), ("transfer_only", "core block only", "^")):
    xs = [e9["variants"][f"{k}_r{r}"]["column_fraction_mean"] for r in e9["radii"]]; ys = [e9["variants"][f"{k}_r{r}"]["corrected_freq_rms"] for r in e9["radii"]]
    ax.plot(xs, ys, marker=mk, label=label)
ax.axhline(e9["variants"]["zero"]["corrected_freq_rms"], color="grey", ls=":", label="no correction"); ax.set_xlabel("fraction of Hessian columns probed (r = 0…4 bonds)")
ax.set_ylabel("corrected ω RMS (cm⁻¹)"); ax.set_yscale("log"); ax.legend(fontsize=8); ax.set_title("E9: a substituted molecule's correction from its core plus a neighbourhood", fontsize=9)
fig.tight_layout(); fig.savefig("figures/e9_core_transfer.png", dpi=150); plt.show()""")
md("""*Reading.* With the parent core's block carried over, probing the Hessian columns of the atoms within two bonds of the substituent — a quarter of
the molecule — reproduces the corrected frequencies to 1.7 cm⁻¹ against 23 for no correction; the substituent's own atoms alone (an eighth) give 2.2.
Either half alone fails (19 and 10 cm⁻¹). The energy-only variant, which is what a local coupled-cluster method can measure, keeps the saving when
the near–far couplings come from the core. In the language of this module: the target is not only local in its pattern (section 7) but additive
across the molecule, which is what makes a label cheap.""")
md("""### 9.2 E10 — measure each environment once, assemble the correction""")
code("""e10 = json.load(open(E9D / "e10_environment_once_2026-09-24.json", encoding="utf-8")); e10t = json.load(open(E9D / "e10_environment_once_2026-09-24_nearest-torsion.json", encoding="utf-8"))
rows = []
for X, v in e10t["by_substituent"].items():
    rows.append(dict(substituent=X, receivers=v["a_assembled"]["n"], **{"assembled: corrected ω RMS": round(v["a_assembled"]["corrected_freq_rms"], 2), "assembled: ring coupling ratio": round(v["a_assembled"]["coupling_ratio"], 2),
                                                                      "own block (ceiling): corrected ω RMS": round(v["b_own_block"]["corrected_freq_rms"], 2)}))
e10_tab = pd.DataFrame(rows).sort_values("assembled: corrected ω RMS").reset_index(drop=True)
a_reg = e10["variants"]["a_assembled"]; a_tor = e10t["variants"]["a_assembled"]; ceil = e10t["variants"]["b_own_block"]
print(f"registered rule (smallest host as donor): {a_reg['corrected_freq_rms']:.2f} cm⁻¹, ratio {a_reg['coupling_ratio']:.2f} on {e10['n_receivers']} receivers → {e10['verdict']}")
print(f"post-hoc, torsion-matched donor within the environment class: {a_tor['corrected_freq_rms']:.2f} cm⁻¹, ratio {a_tor['coupling_ratio']:.2f} on {e10t['n_receivers']} receivers; ceiling with the receiver's own block {ceil['corrected_freq_rms']:.2f}")
display(e10_tab)""")
md("""*Reading.* Between, as registered (3.75 cm⁻¹ against a bar of 3.3), and the per-substituent table says why: the planar and rigid substituents
transplant to 1.8–3.1 cm⁻¹, within a cm⁻¹ of the ceiling, while the rotors (CH₃, OCH₃, SH, CONH₂) do not — their block depends on the conformation
more finely than a rotated donor block captures. For eleven of fifteen environment types the label price becomes a property of the environment, not
of the molecule; for the rotors it stays per molecule or per conformer. This is the data argument for the "environment once" strategy of the
project's long-term note, and its limit.""")
md("""### 9.3 Size extrapolation — a pair model trained on ≤ 26 atoms, read on 27–34""")
code("""SZ = json.load(open(Path("..") / "out" / "E7_rungB_size26_2026-09-25.json", encoding="utf-8"))
rows = []
for n in SZ["sizes"]:
    ma = SZ["curve"][str(n)]["B1_mlp"]["mean"]["a"]; mb = SZ["curve"][str(n)]["B1_mlp"]["mean"]["b"]
    rows.append({"training molecules (≤ 26 atoms)": n, "> 26 atoms: ring coupling ratio": round(ma["coupling_ratio"], 2), "> 26 atoms: corrected ω RMS": round(ma["corrected_freq_rms"], 2),
                 "≤ 26 scaffolds (control): ratio": round(mb["coupling_ratio"], 2), "≤ 26 scaffolds: corrected ω RMS": round(mb["corrected_freq_rms"], 2)})
sz_tab = pd.DataFrame(rows)
print(f"hold-out: {len(SZ['holdout_a'])} molecules of 27–34 atoms; control: {len(SZ['holdout_b'])} scaffold molecules ≤ 26; pool {SZ['pool']}; zero rule {SZ['zero_rule']['a']['corrected_freq_rms']:.1f} / {SZ['zero_rule']['b']['corrected_freq_rms']:.1f} cm⁻¹")
display(sz_tab)
fig, ax = plt.subplots(figsize=(5.0, 3.2))
ax.plot(SZ["sizes"], [SZ["curve"][str(n)]["B1_mlp"]["mean"]["a"]["coupling_ratio"] for n in SZ["sizes"]], marker="o", label="27–34 atoms (extrapolation)")
ax.plot(SZ["sizes"], [SZ["curve"][str(n)]["B1_mlp"]["mean"]["b"]["coupling_ratio"] for n in SZ["sizes"]], marker="s", label="≤ 26 atoms, unseen scaffolds (control)")
ax.set_xscale("log"); ax.set_xlabel("training molecules (≤ 26 atoms)"); ax.set_ylabel("ring coupling ratio to the zero rule"); ax.set_ylim(0, 1.05); ax.legend(fontsize=8)
ax.set_title("Size extrapolation of the pair model", fontsize=9); fig.tight_layout(); fig.savefig("figures/size_extrapolation.png", dpi=150); plt.show()""")
md("""*Reading.* Encouraging on the registered bars, at the edge: ratio 0.66 → 0.62 → 0.59 and corrected RMS 6.6 → 6.0 → 5.8 cm⁻¹ on the larger
molecules for 45 → 100 → 161 small training molecules, against 0.40 → 0.36 and 5.7 → 4.5 within size. Size costs about 0.2 in ratio and a cm⁻¹ at
this range, and the curve is shallow. This is the first cut of the size hold-out of the proof-of-learning pre-registration; the decisive curve — layer
B of the corpus, 100 to 1,200 small molecules, three hold-outs, reading rule on record — started the same morning on two rented machines.""")
md("""### 9.4 What we learned (continued)

- **Locality makes labels additive.** A substituted molecule's correction is its core's block plus a neighbourhood (E9), and for rigid substituents
  that neighbourhood is a property of the environment, measurable once (E10). The cost of a coupled-cluster label then scales with the
  environment, not the molecule — the argument that turns the expensive labels into a growing asset rather than a per-molecule price.
- **Small teaches large, slowly.** Trained on ≤ 26 atoms the pair model carries to 27–34 atoms at 0.59 ratio; within size it reaches 0.36. The gap is
  the size axis of the mandate, and it is now a number that a longer learning curve can move.
- **A proof of learning is a pre-registered curve, not a table.** Three follow-up days each moved a number; none of them is the proof. The
  layer-B run and its reading rule are.""")
code("""followup3 = dict(e9=dict(verdict_r2=e9["verdict_r2"], n=e9["n_admitted"], r2=e9["variants"]["transfer_probe_r2"], r0=e9["variants"]["transfer_probe_r0"], energy_only_r2=d2),
                 e10=dict(verdict=e10["verdict"], registered=a_reg, nearest_torsion=a_tor, ceiling=ceil, n_receivers=e10t["n_receivers"],
                          within_bars=[X for X, v in e10t["by_substituent"].items() if v["a_assembled"]["corrected_freq_rms"] <= 3.3 and v["a_assembled"]["coupling_ratio"] <= 0.5]),
                 size_extrapolation=dict(sizes=SZ["sizes"], holdout_a=len(SZ["holdout_a"]), holdout_b=len(SZ["holdout_b"]), pool=SZ["pool"],
                                         a={str(n): SZ["curve"][str(n)]["B1_mlp"]["mean"]["a"] for n in SZ["sizes"]}, b={str(n): SZ["curve"][str(n)]["B1_mlp"]["mean"]["b"] for n in SZ["sizes"]}))
json.dump(followup3, open("results_followup3.json", "w"), indent=1); print("results_followup3.json written")""")

nb = new_notebook(cells=cells, metadata={"kernelspec": {"name": "python3", "display_name": "Python 3", "language": "python"}})
path = HERE / "deep_learning.ipynb"
nbformat.write(nb, path)
if "--no-execute" not in sys.argv:
    NotebookClient(nb, timeout=3600, kernel_name="python3", resources={"metadata": {"path": str(HERE)}}).execute()
    nbformat.write(nb, path)
    print("executed and written:", path)
else:
    print("written (not executed):", path)
